development:
  adapter: mysql2
  database: myapp_development
  username: root
  password: chess
  host: localhost

test: &test
  adapter: mysql2
  database: myapp_test
  username: root
  password: chess
  host: localhost
